# Generated by Django 3.2.1 on 2021-05-08 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 15, 23, 57, 758263))),
            ],
        ),
    ]
