# Generated by Django 3.2.1 on 2021-05-06 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 21, 5, 59, 531823)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(),
        ),
    ]
