# Generated by Django 3.2.1 on 2021-05-07 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 6, 16, 35, 665511)),
        ),
    ]
